CREATE TABLE positions (
   id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   nazwa VARCHAR(32) UNIQUE,
   pensja NUMBER(6) DEFAULT 2000 NOT NULL
);

CREATE TABLE workers (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  pesel VARCHAR(11) UNIQUE,
  imie VARCHAR2(32) NOT NULL,
  nazwisko VARCHAR2(32) NOT NULL,
  data_zatrudnienia DATE DEFAULT SYSDATE NOT NULL,
  premia NUMBER(6) DEFAULT NULL,
  id_position REFERENCES  positions(id) NOT NULL,
  id_team NUMBER DEFAULT NULL
);

CREATE TABLE teams (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nazwa VARCHAR2(32) UNIQUE,
  data_utworzenia DATE DEFAULT SYSDATE NOT NULL,
  id_leader REFERENCES workers(id)
);

ALTER TABLE workers ADD CONSTRAINT fk_id_team FOREIGN KEY (id_team) REFERENCES teams(id);

CREATE TABLE projects (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nazwa VARCHAR(32) UNIQUE,
  data_rozpoczecia DATE DEFAULT SYSDATE NOT NULL,
  data_zakonczenia DATE DEFAULT NULL,
  id_team REFERENCES teams(id)
);


CREATE TABLE holidays (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_worker REFERENCES workers(id) NOT NULL,
  czas_rozpoczecia DATE DEFAULT SYSDATE NOT NULL,
  czas_zakonczenia DATE NOT NULL
);

DROP TABLE workers;
DROP TABLE teams;
DROP TABLE projects;
DROP TABLE positions;
DROP TABLE holidays;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME ='inf127345.workers';
